export * from './deleteProducto';
export * from './getAllProductos';
export * from './getCategoriaGenero';
export * from './getGenero';
export * from './getOneProducto';
export * from './getProductosCategoria';
export * from './getProductosGenero';
export * from './getReferencias';
export * from './getTallas';